import { StyleSheet } from 'react-native';
export default StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
    backgroundColor: '#ffffff',
    alignItems: 'center',
  },
  scrollContainer: {
    alignItems: 'center',
    paddingBottom: 100,
  },
  hiText: {
    fontSize: 22,
    fontWeight: 'bold',
    alignSelf: 'flex-start',
    marginBottom: 5,
  },
  welcomeText: {
    fontSize: 26,
    fontWeight: 'bold',
    color: '#555',
    alignSelf: 'flex-start',
    marginBottom: 25,
  },
  featureButton: {
    width: '40%',
    aspectRatio: 1,
    borderRadius: 20,
    backgroundColor: '#EDE8D0',
    alignItems: 'center',
    justifyContent: 'center',
    margin: 12,
    padding: 10,
  },
  buttonIcon: {
    width: 60,
    height: 60,
    marginBottom: 8,
  },
  buttonText: {
    fontSize: 12,
    color: '#333',
    textAlign: 'center',
    fontWeight: 'bold',
  },
  bottomNav: {
    position: 'absolute',
    bottom: 10,
    width: '90%',
    flexDirection: 'row',
    justifyContent: 'space-around',
    backgroundColor: '#EDE8D0',
    paddingVertical: 12,
    borderRadius: 18,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 6,
  },
  navButton: {
    padding: 12,
  },
});
